version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env.example

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    env_file: .env.example

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
